package com.infinitiessoft.btrs.model;
// Generated Jul 9, 2012 10:51:06 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ExpenseTypes generated by hbm2java
 */
@Entity
@Table(name = "expense_types")
public class ExpenseType implements java.io.Serializable {

	private static final long serialVersionUID = -7100716660369786371L;
	
	private Long id;
	private ExpenseCategory expenseCategory;
	private String nameKey;
	private String code;
	private String comment;
	private Set<Expense> expenses = new HashSet<Expense>(0);
	private List<TypeParameter> typeParameters = new ArrayList<TypeParameter>(0);

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public ExpenseCategory getExpenseCategory() {
		return this.expenseCategory;
	}

	public void setExpenseCategory(ExpenseCategory expenseCategory) {
		this.expenseCategory = expenseCategory;
	}

	@Column(name = "name_key", length = 100)
	@NotNull
	@Length(max = 100)
	public String getNameKey() {
		return this.nameKey;
	}

	public void setNameKey(String nameKey) {
		this.nameKey = nameKey;
	}
	
	@Column(name = "code", length = 100, unique = true)
	@NotNull
	@Length(max = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	
	@Column(length = 4000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expenseType")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}
	
	@ManyToMany(targetEntity = TypeParameter.class, fetch = FetchType.LAZY)
	@JoinTable(name = "exp_types_type_parameters",
		joinColumns = @JoinColumn(name = "type_id"),
		inverseJoinColumns = @JoinColumn(name = "parameter_id"))
	public List<TypeParameter> getTypeParameters() {
		return typeParameters;
	}

	public void setTypeParameters(List<TypeParameter> typeParameters) {
		this.typeParameters = typeParameters;
	}

}
