package com.infinitiessoft.btrs.model;

// Generated Jul 9, 2012 10:51:06 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ExpenseTypes generated by hbm2java
 */
@Entity
@Table(name = "expense_categories")
public class ExpenseCategory implements java.io.Serializable {

	private static final long serialVersionUID = -8880786274284098835L;

	private Long id;
	private String nameKey;
	private String comment;
	private Set<ExpenseType> expenseTypes = new HashSet<ExpenseType>(0);
	

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name_key", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNameKey() {
		return this.nameKey;
	}

	public void setNameKey(String nameKey) {
		this.nameKey = nameKey;
	}
	
	
	@Column(length = 4000)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expenseCategory")
	public Set<ExpenseType> getExpenseTypes() {
		return this.expenseTypes;
	}

	public void setExpenseTypes(Set<ExpenseType> expenseTypes) {
		this.expenseTypes = expenseTypes;
	}

}
