package com.infinitiessoft.btrs.model;
// Generated Jul 9, 2012 10:51:06 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.security.management.RoleName;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles")
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = -4458069011477017587L;
	
	private Long id;
	private String name;
	private String comment;
	private List<User> users = new ArrayList<User>(0);

	public Role() {
	}

	public Role(Long id, String name) {
		this.id = id;
		this.name = name;
	}
	public Role(Long id, String name, String comment, List<User> users) {
		this.id = id;
		this.name = name;
		this.comment = comment;
		this.users = users;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@RoleName
	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(length = 4000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public List<User> getUsers() {
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

}
