package com.infinitiessoft.btrs.model;
// Generated Jul 9, 2012 10:51:06 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.NotNull;
import org.jboss.seam.annotations.security.management.RoleName;

import com.infinitiessoft.btrs.enums.RoleEnum;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles")
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = -4458069011477017587L;
	
	private Long id;
	private RoleEnum value;
	private List<User> users;

	

	public Role() {}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Transient
	public String getNameKey() {
		return this.value.getLabel();
	}
	
	@RoleName
	@Enumerated(EnumType.STRING)
	@Column(name = "value", nullable = false)
	@NotNull
	public RoleEnum getValue() {
		return value;
	}

	public void setValue(RoleEnum value) {
		this.value = value;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public List<User> getUsers() {
		if (users == null) {
			users = new ArrayList<User>(0);
		}
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

}
