package com.infinitiessoft.btrs.enums;

public enum ExcelStylesNames {

	TITLE, CREATED_DATE_NAME, CREATED_DATE_VALUE, REASON_NAME, REASON_VALUE, ROUTE_NAME, ROUTE_VALUE,
	TRAVEL_DATE, START_NAME, START_VALUE, END_NAME, END_VALUE, FORM_COMMENT_NAME, FORM_COMMENT_VALUE,
	SUMMARY, AMOUNT, TAX, COMMENT, EXPENSE_CATEGORY, EXPENSE_TYPE, MONEY, COMMENT_VALUE, PERSONS_NAME,
	PERSONS_VALUE, DAYS_NAME, DAYS_VALUE, TOTAL, STATUS_NAME, STATUS_VALUE, ACCONUTANT_NAME,
	ACCOUNTANT_VALUE, APPLICANT_NAME, APPLICANT_VALUE, DEFAULT
}
